<a href="https://colab.research.google.com/github/bhargav210708/EDA-PROJECT/blob/main/Exp4_28_7_2026(25BDS0152).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(42)

In [ ]:
data =[[120,250,310],
       [450,180,220],
       [300,410,150],
       [500,290,380],
       [160,290,490]
       ]
dfx=pd.DataFrame(data,index=['Laptop','Phone','Tablet','Monitor','Printer'],
                 columns=['New_York','London','Tokyo'])
print("---Initial DataFrame---")
print(dfx)
print("\n"+"=*40"+"\n")

---Initial DataFrame---
         New_York  London  Tokyo
Laptop        120     250    310
Phone         450     180    220
Tablet        300     410    150
Monitor       500     290    380
Printer       160     290    490

=*40

In [ ]:
dfx['Paris']=np.nan
dfx.loc['HeadPhones']=[210,340,190,420]
dfx.loc['Camera']=np.nan
dfx['Sydney']=np.nan
dfx.loc['Laptop','Paris']=175.0
print("---DataFrame with missing VALUES (NaN)---")
print(dfx)
print("\n"+"=*40"+"\n")

---DataFrame with missing VALUES (NaN)---
            New_York  London  Tokyo  Paris  Sydney
Laptop         120.0   250.0  310.0  175.0     NaN
Phone          450.0   180.0  220.0    NaN     NaN
Tablet         300.0   410.0  150.0    NaN     NaN
Monitor        500.0   290.0  380.0    NaN     NaN
Printer        160.0   290.0  490.0    NaN     NaN
HeadPhones     210.0   340.0  190.0  420.0     NaN
Camera           NaN     NaN    NaN    NaN     NaN

=*40

In [ ]:
dfx.isnull()

            New_York  London  Tokyo  Paris  Sydney
Laptop         False   False  False  False    True
Phone          False   False  False   True    True
Tablet         False   False  False   True    True
Monitor        False   False  False   True    True
Printer        False   False  False   True    True
HeadPhones     False   False  False  False    True
Camera          True    True   True   True    True

In [ ]:
dfx.notnull()

            New_York  London  Tokyo  Paris  Sydney
Laptop          True    True   True   True   False
Phone           True    True   True  False   False
Tablet          True    True   True  False   False
Monitor         True    True   True  False   False
Printer         True    True   True  False   False
HeadPhones      True    True   True   True   False
Camera         False   False  False  False   False

In [ ]:
dfx.isnull().sum()

New_York    1
London      1
Tokyo       1
Paris       5
Sydney      7
dtype: int64

In [ ]:
dfx.isnull().sum().sum()

np.int64(15)

In [ ]:
dfx.count()

New_York    6
London      6
Tokyo       6
Paris       2
Sydney      0
dtype: int64

In [ ]:
dfx.Paris[dfx.Paris.notnull()]

Laptop        175.0
HeadPhones    420.0
Name: Paris, dtype: float64

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [New_York, London, Tokyo, Paris, Sydney]
Index: []

In [ ]:
dfx.dropna(how='all')

            New_York  London  Tokyo  Paris  Sydney
Laptop         120.0   250.0  310.0  175.0     NaN
Phone          450.0   180.0  220.0    NaN     NaN
Tablet         300.0   410.0  150.0    NaN     NaN
Monitor        500.0   290.0  380.0    NaN     NaN
Printer        160.0   290.0  490.0    NaN     NaN
HeadPhones     210.0   340.0  190.0  420.0     NaN

In [ ]:
dfx.dropna(how='all', axis=1)

            New_York  London  Tokyo  Paris
Laptop         120.0   250.0  310.0  175.0
Phone          450.0   180.0  220.0    NaN
Tablet         300.0   410.0  150.0    NaN
Monitor        500.0   290.0  380.0    NaN
Printer        160.0   290.0  490.0    NaN
HeadPhones     210.0   340.0  190.0  420.0
Camera           NaN     NaN    NaN    NaN

In [ ]:
dfx.dropna(thresh=5, axis=1)

            New_York  London  Tokyo
Laptop         120.0   250.0  310.0
Phone          450.0   180.0  220.0
Tablet         300.0   410.0  150.0
Monitor        500.0   290.0  380.0
Printer        160.0   290.0  490.0
HeadPhones     210.0   340.0  190.0
Camera           NaN     NaN    NaN

In [ ]:
ar1 = np.array([190,420,630,np.nan,900])
ser1 = pd.Series(ar1)
ar1.mean()
ser1.mean()

np.float64(535.0)

In [ ]:
ser2 =dfx.Paris
ser2.sum()
ser2.mean()
ser2.cumsum()

Laptop        175.0
Phone           NaN
Tablet          NaN
Monitor         NaN
Printer         NaN
HeadPhones    595.0
Camera          NaN
Name: Paris, dtype: float64

In [ ]:
filledDf = dfx.fillna(0)
filledDf
dfx.Paris.fillna(method='ffill')
dfx.Paris.fillna(method='bfill')

/tmp/ipykernel_568/1903518481.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Paris.fillna(method='ffill')
/tmp/ipykernel_568/1903518481.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Paris.fillna(method='bfill')

Laptop        175.0
Phone         420.0
Tablet        420.0
Monitor       420.0
Printer       420.0
HeadPhones    420.0
Camera          NaN
Name: Paris, dtype: float64

In [ ]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,SimpleImputer
df = pd.DataFrame({

                   "Character ":['Tony','Peter','Thor',np.nan,np.nan],
                  "Age" :[np.nan,22,1500,47,np.nan],
                   "Experience":[10,5,1300,np.nan,np.nan],


})

In [ ]:
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
print(df["Age_Mean"])

0     523.0
1      22.0
2    1500.0
3      47.0
4     523.0
Name: Age_Mean, dtype: float64

In [ ]:
median_imputer = SimpleImputer(strategy="median")
df["Experience_Median"] = median_imputer.fit_transform(df[["Experience"]])
print(df["Experience_Median"])

0      10.0
1       5.0
2    1300.0
3      10.0
4      10.0
Name: Experience_Median, dtype: float64

In [ ]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Age_Mode"] = mode_imputer.fit_transform(df[["Age"]])
print(df["Age_Mode"])

0      22.0
1      22.0
2    1500.0
3      47.0
4      22.0
Name: Age_Mode, dtype: float64

In [ ]:
num_cols = ["Age", "Experience"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Expeience_MICE"] = df_mice["Experience"]
print(df)

  Character      Age  Experience  Age_Mean  Experience_Median  Age_Mode  \
0       Tony     NaN        10.0     523.0               10.0      22.0
1      Peter    22.0         5.0      22.0                5.0      22.0
2       Thor  1500.0      1300.0    1500.0             1300.0    1500.0
3        NaN    47.0         NaN      47.0               10.0      47.0
4        NaN     NaN         NaN     523.0               10.0      22.0

      Age_MICE  Expeience_MICE
0    27.565528       10.000000
1    22.000000        5.000000
2  1500.000000     1300.000000
3    47.000000       26.965347
4   399.141382      335.491337